# tasks file
---
- name: install | dependencies (pre)
  apt:
    name: "{{ haproxy_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - haproxy-repository-install-dependencies

- name: install | Create Repo Key Directory
  file:
    path: /etc/apt/trusted.gpg.d
    state: directory

- name: install | Download Debian Signing Key
  get_url:
    url: https://haproxy.debian.net/bernat.debian.org.gpg
    dest: /etc/apt/trusted.gpg.d/haproxy-official-repo.key
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Set zabbix repo file for Debian
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/haproxy-official-repo.key] http://haproxy.debian.net {{ ansible_distribution_release | lower }}-backports-{{ haproxy_version }} main"
    state: present
    filename: haproxy-repo
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install | dependencies
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies

- name: install | additional
  apt:
    name: "{{ haproxy_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - haproxy-install-additional

- name: Add HaProxy Shared Group
  ansible.builtin.group:
    name: haproxy-shared
    state: present
    gid: 10493

- name: Add HaProxy User to Shared Group
  ansible.builtin.user:
    name: haproxy
    group: haproxy-shared
    append: true