# tasks file
---
- name: check version support
  fail:
    msg: "HAProxy version {{ haproxy_version }} is not supported"
  when: haproxy_version | string not in haproxy_versions_supported
  tags:
    - configuration
    - haproxy
    - haproxy-check-version-support

- import_tasks: install.yml
  tags:
    - configuration
    - haproxy
    - haproxy-install

- import_tasks: acl.yml
  tags:
    - configuration
    - haproxy
    - haproxy-acl

- import_tasks: blacklist.yml
  tags:
    - configuration
    - haproxy
    - haproxy-blacklist

- import_tasks: copy_files.yml
  tags:
    - configuration
    - haproxy
    - haproxy-copy

- include_tasks: k8s.yml
  when:
    - haproxy_k8s_enable is defined
    - haproxy_k8s_enable | bool
  tags:
    - configuration
    - haproxy-configuration    

- import_tasks: configuration.yml
  tags:
    - configuration
    - haproxy
    - haproxy-configuration

- name: Run job of k8s service enabled
  shell: /bin/bash /etc/haproxy/gateway-haproxy-config-cron
  when:
  when:
    - haproxy_k8s_enable is defined
    - haproxy_k8s_enable | bool
  tags:
    - configuration
    - haproxy-configuration    

- name: start and enable service
  service:
    name: haproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - haproxy
    - haproxy-start-enable-service
